### ISSUE TITLE
box-sizing

### ISSUE THREAD

**Issue by necipsagiro** [25bahaz/node101-challenges#3]
[`box-sizing`](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing)in ne olduğuna bak, biz `border-box` kullanıyoruz, sebebini `box-sizing`e bakınca anlarsın :D

css'in de başına bunu eklersen iyi olur:

* {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}

**Comment by 25bahaz** [comment]
box sizing'i inceledim anladım kullanım sebebini
